language: ruby

rvm:
  - 2.2.0

before_script:
  - curl -sSL https://raw.githubusercontent.com/alto/travis-solr/handle_multiple_solr_confs_correctly/travis-solr.sh | SOLR_VERSION=4.9.1 SOLR_CORE=core0 SOLR_CONFS="$TRAVIS_BUILD_DIR/config/travis/schema.xml" bash
  - echo "--------------"
  - echo $(curl "http://localhost:8983/solr/admin/cores")
  - echo $(curl "http://localhost:8983/solr/core0/select?q=dude")
  - echo $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8983/solr")
  - echo $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8983/solr/")
  - echo $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8983/solr/development")
  - echo $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8983/solr/test")
  - echo $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8983/solr/test/")
  - echo $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8983/solr/default")
  - echo $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8983/solr/core0")
  - echo "--------------"
  - mysql -e 'create database travis_solr_test;' -uroot
  # - bundle install --without development
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rake db:fixtures:load
  - RAILS_ENV=test bundle exec rake sunspot:reindex
  - echo $(curl "http://localhost:8983/solr/core0/select?q=dude")
