language: ruby

rvm:
  - 2.2.0

before_script:
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.9.1 bash
  - mysql -e 'create database travis_solr_test;' -uroot
  - bundle install --without development
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rake db:fixtures:load
  - RAILS_ENV=test bundle exec rake sunspot:reindex
