development:
  adapter: mysql2
  database: travis_solr_development
  username: root
  password:
  socket: /tmp/mysql.sock
  reconnect: true
  # host: 127.0.0.1

test:
  adapter: mysql2
  database: travis_solr_test
  username: root
  password:
  # socket: /tmp/mysql.sock
  reconnect: true
  host: 127.0.0.1 # for CI servers!!
